function extract_video_timestamps(behav_path)
% EXTRACT_VIDEO_TIMESTAMPS Parse FFmpeg timestamp output into MATLAB array
%
% Syntax:
%   extract_video_timestamps(behav_path)
%
% Description:
%   Reads the CSV file generated by FFmpeg's ffprobe command and converts
%   frame timestamps into a MATLAB array. The timestamps provide precise
%   temporal information for each video frame, enabling accurate
%   synchronization with calcium imaging acquisition at 10Hz.
%
% Input:
%   behav_path - String specifying directory containing timestamp CSV file
%                (generated by FFmpeg batch file execution)
%
% Output Files:
%   timestamps.mat - Located in Matt_files subdirectory, contains:
%                    'timestamps' - Nx1 double array of frame times (seconds)
%
% FFmpeg Command Reference:
%   The batch file should execute:
%   ffprobe -select_streams v:0 -show_entries frame=pts_time -of csv=p=0 video.avi > timestamps.csv
%
%   This extracts presentation timestamp (PTS) for each video frame
%
% CSV Format:
%   Simple single-column format (no headers):
%   0.000000
%   0.050000
%   0.100000
%   ...
%
% Algorithm:
%   1. Locate timestamp CSV file in behavioral directory
%   2. Read CSV using readmatrix (handles numeric data)
%   3. Validate timestamps are monotonically increasing
%   4. Save to Matt_files subdirectory for pipeline access
%
% Example:
%   behav_path = 'D:\AD_6\AD21\1L1R\TEST';
%   extract_video_timestamps(behav_path);
%
% Notes:
%   - Requires FFmpeg batch file to have been executed first
%   - CSV filename must contain 'timestamp' (case-insensitive)
%   - Validates timestamp consistency (no negative intervals)
%   - Typical video frame rate ~20 Hz (50ms intervals)
%   - Imaging frame rate is 10 Hz (100ms intervals)
%
% See also: batch_file_handler, readmatrix, synchronize_behavior_imaging

% Define paths
brain_path = fullfile(behav_path, 'Matt_files');

% Create Matt_files directory if it doesn't exist
if ~exist(brain_path, 'dir')
    mkdir(brain_path);
    fprintf('Created directory: %s\n', brain_path);
end

% Navigate to behavioral data directory
cd(behav_path);

% Locate timestamp CSV file
csv_files = dir('*timestamp*.csv');

if isempty(csv_files)
    error(['No timestamp CSV file found in %s\n', ...
           'Expected filename pattern: *timestamp*.csv\n', ...
           'Please run FFmpeg batch file first using batch_file_handler()'], ...
           behav_path);
end

if length(csv_files) > 1
    warning('Multiple timestamp CSV files found. Using first: %s', csv_files(1).name);
end

csv_filename = csv_files(1).name;
fprintf('Reading timestamps from: %s\n', csv_filename);

% Read timestamp data
try
    % Read numeric CSV data (no headers expected)
    timestamps = readmatrix(csv_filename);
    
    % Validate data
    if isempty(timestamps)
        error('Timestamp file is empty');
    end
    
    % Ensure column vector
    if size(timestamps, 2) > 1
        warning('Multiple columns detected. Using first column only.');
        timestamps = timestamps(:, 1);
    end
    
    % Convert to column vector if needed
    timestamps = timestamps(:);
    
catch read_error
    error('Failed to read timestamp CSV: %s', read_error.message);
end

% Validate timestamps
fprintf('Validating %d timestamps...\n', length(timestamps));

% Check for NaN or Inf values
if any(isnan(timestamps))
    error('Timestamp data contains NaN values');
end

if any(isinf(timestamps))
    error('Timestamp data contains infinite values');
end

% Check for monotonically increasing timestamps
time_diffs = diff(timestamps);
if any(time_diffs < 0)
    warning('Timestamps are not monotonically increasing. Check video file integrity.');
end

% Report statistics
fprintf('=== TIMESTAMP STATISTICS ===\n');
fprintf('Total frames: %d\n', length(timestamps));
fprintf('First timestamp: %.6f s\n', timestamps(1));
fprintf('Last timestamp: %.6f s\n', timestamps(end));
fprintf('Video duration: %.2f s (%.2f min)\n', ...
        timestamps(end) - timestamps(1), ...
        (timestamps(end) - timestamps(1)) / 60);

% Calculate frame rate statistics
median_interval = median(time_diffs);
median_fps = 1 / median_interval;
fprintf('Median frame interval: %.4f s\n', median_interval);
fprintf('Estimated frame rate: %.2f Hz\n', median_fps);

% Check for dropped frames or irregularities
frame_rate_std = std(time_diffs);
if frame_rate_std > 0.01
    warning(['High frame rate variability detected (std = %.4f s).\n', ...
             'This may affect synchronization quality.'], frame_rate_std);
end

% Save timestamps to Matt_files directory
cd(brain_path);
save('timestamps.mat', 'timestamps');

fprintf('✓ Timestamps saved to: %s\n', fullfile(brain_path, 'timestamps.mat'));

% Return to behavioral directory
cd(behav_path);

end